basePath: /api/v1
definitions:
  Response:
    properties:
      code:
        type: integer
      data: {}
      message: {}
    type: object
  model.LoginU1:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.LoginU2:
    properties:
      code:
        type: string
      mail_addr:
        type: string
    type: object
  model.SendMailAddr:
    properties:
      mail_addr:
        type: string
    type: object
  model.SignupUser:
    properties:
      mail_addr:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: 8.146.198.169
info:
  contact:
    email: SJMbaiyang@163.com
    name: KitZhangYs
  description: 偶遇华夏API
  termsOfService: http://swagger.io/terms/
  title: oyhx API
  version: "1.0"
paths:
  /api/v1/code_login:
    post:
      description: 通过邮箱验证码登录，验证码正确则获得token（注：该接口用于发送验证码之后）
      parameters:
      - description: 登录结构体
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/model.LoginU2'
      responses:
        "200":
          description: '{"message":"登陆成功，获得token"}'
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: '{"message":"Failure"}'
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: '{"message":"Failure"}'
          schema:
            $ref: '#/definitions/Response'
      summary: 邮箱验证码登录
      tags:
      - login
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: 登录并获得token
      parameters:
      - description: 登录结构体
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/model.LoginU1'
      responses:
        "200":
          description: '{"message":"登陆成功，获得token"}'
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: '{"message":"Failure"}'
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: '{"message":"Failure"}'
          schema:
            $ref: '#/definitions/Response'
      summary: 账号密码登录
      tags:
      - login
  /api/v1/send_mail:
    post:
      description: 向用户提供的邮箱地址发送一个验证码
      parameters:
      - description: 邮箱地址
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/model.SendMailAddr'
      responses:
        "200":
          description: '{"message":"登陆成功，获得token"}'
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: '{"message":"Failure"}'
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: '{"message":"Failure"}'
          schema:
            $ref: '#/definitions/Response'
      summary: 发送邮箱验证码
      tags:
      - login
  /api/v1/signup:
    post:
      description: 新用户进行注册
      parameters:
      - description: 用户信息
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/model.SignupUser'
      responses:
        "200":
          description: '{"message":"注册成功"}'
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: '{"message":"Failure"}'
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: '{"message":"Failure"}'
          schema:
            $ref: '#/definitions/Response'
      summary: 新用户注册
      tags:
      - signup
swagger: "2.0"
